rstudio/learnr

inst/lib/tutor/tutor.js

@kevinushey It seems like this variable isn't referenced anywhere so this is the only change necessary, let me know if there is anything I missed.
I prefixed with `$` because `Tutor` actually exposes a public API and I wanted that bit to be private.

use $ prefix for tutor completer since it's private

---

R/events.R
R/http-handlers.R
R/storage.R
inst/lib/tutor/tutor.js
inst/rmarkdown/templates/tutorial/resources/tutorial-format.js

Addresses #44 
@robbyshaver This PR renames the exercise_skipped event to section_skipped. As part of the change your `exerciseSkipped` helper function is no longer called (both `section_completed` and `section_skipped` both call `sectionCompleted`): 
https://github.com/rstudio/tutor/blob/feature/section-skipped/inst/rmarkdown/templates/tutorial/resources/tutorial-format.js#L446-L453
Not sure if this is the right change and/or if other refinements are required. Could you try out this PR locally and let me know if everything is working as you expect and whether we need additional refinement?

rename exercise_skipped to section_skipped

---

inst/lib/tutor/tutor.js

Intended to address https://github.com/rstudio/tutor/issues/56
@robbyshaver I've added the code required for tutorials to save and restore their hash and scroll position in this PR. This appears to work fine, but I thought you might want to give it a test drive to confirm before we merge it. Note that we are now restoring scroll position which previously I thought too janky but if we are restoring the topic it only seems right to restore the scroll position.

save and restore current topic

---

inst/lib/tutorial/tutorial-diagnostics.js
sandbox/sandbox.Rmd

When producing diagnostics for user code, we attempt to strip out comments and whitespace-only tokens (as they are not relevant to the diagnostics engine). Unfortunately, we were over-aggressively stripping tokens that contained any whitespace when the intention was to strip only whitespace-only tokens.
Closes #95.

fix diagnostics comma false-positive

---

NEWS.md
R/tutorial-format.R

This is basically a rip off of rstudio/flexdashboard#150

Use the html4 output format instead of the default html5 in Pandoc 2.0

---

DESCRIPTION
NEWS.md

I've ran the examples in the [examples directory](https://github.com/rstudio/learnr/tree/master/examples/) under Pandoc 1.9 and 2.0. There was no difference.
I've also looked at the code changes between the last version (the first time that `learnr` was released to CRAN), that I tagged here (14413cc). They are really very minor, so I don't think any extra testing is necessary.
Finally, I did `devtools::check()` as CRAN and successfully uploaded the new source package to r-hub.
@jjallaire, if you agree, I can release learnr 0.9.1 to CRAN as soon as this is merged to master. Once CRAN accepts it, I'll tag the current commit as well. (Here's the release checklist I came up with: https://github.com/rstudio/learnr/issues/131)

Version bump to 0.9.1: ready to release to CRAN when merged

---

NEWS.md
inst/htmlwidgets/quiz.js

This was a quick fix on the JS side: essentially grab the .html() provided by the `incorrect` (and the`correct`) arguments to `question()`. Previously, we were grabbing the .text(), which stripped the html rich formatting when provided.
@jjallaire, this seemed like low hanging fruit for this release. Let me know if you think that it risks regression or anything else I might have overlooked.
Closes #136.

Display full HTML messages if provided by the `incorrect` or the `correct` args to `question() `

---

R/http-handlers.R
inst/lib/tutorial/tutorial.js

We do this by allowing `$serverRequest()` calls only after the Shiny server has been fully initialized; our method to guarantee this for `learnr` is to send a custom message at the end of the `register_http_handlers()` function (which is in R), that works as a "bat signal" for the JS side to know when to proceed with calls to `$serverRequest()`.

Fix 500 errors when reloading tutorial

---

NEWS.md
R/exercise.R

Fixes this warning:
```
[WARNING] This document format requires a nonempty <title> element.
Please specify either 'title' or 'pagetitle' in the metadata.
Falling back to 'exercise.knit.utf8'
```
Tested under Pandoc 2.0.4 and 1.19.2.1, on Mac.

Fix #154: pandoc warning during exercise knit

---

R/exercise.R
R/utils.R
docs/exercises.Rmd
docs/snippets/exercisefeedback.md

Fixes #163
Submits a copy of the exercise environment before the submission is rendered.  This gives a fresh environment for the checker to user that contains the setup code.

Add `envir_prep` to checker function call

---

R/initialize.R

Include names in deparse results. (Previously names were dropped, so metadata was passed on incorrectly.) 
Fixes #182

Fix for #182

---

DESCRIPTION

Fixes #225
Dev packrat that will check for deps within _broken_ rmd files that work correctly within learnr.
(Checks for deps by chunk not by whole tangled R file)

Require packrat dev version

---

NEWS.md
inst/rmarkdown/templates/tutorial/resources/tutorial-format.css

override shiny-input-container width to 100%

---

NEWS.md
R/quiz.R

When questions are tried again, the existing answer will remain.
Before this PR, when questions where initialized, they were always initialized with a NULL answer.  If the user was to get the answer wrong and try again, the question would be completely reset.  This PR makes it so that the question is reset, but the existing answer remains.
PR task list:

Do not reset question submissions

---

inst/tutorials/ex-setup-r/ex-setup-r.Rmd

* Adds link to tutorial's source code
* Removes claim that the tutorial has a "Run Code" section (it does not)
* Improves answer messages to Where do you download R? quiz and allows retries
These changes do not merit a NEWS entry or unit tests.

Text edits to ex-setup-r tutorial

---

R/exercise.R

Fixes #286
Reprex:
```r
rmarkdown::run("fixed286.Rmd")
```
````rmd
---
---
```{r setup, include=FALSE}
library(kableExtra)
```
```{r kable_exercise, exercise = TRUE}
iris %>%
head() %>%
kable(caption = "") %>%
kable_styling(bootstrap_options = "striped", full_width = FALSE)
```
````

Maintain knitr's output handler

---

NEWS.md
R/exercise.R

Removes warning generated when evaluating exercises:
```
[WARNING] This document format requires a nonempty <title> element.
Please specify either 'title' or 'pagetitle' in the metadata.
Falling back to 'exercise.knit.utf8'
```
PR task list:

remove pandoc generated warning when evaluating exercises

---

NEWS.md
R/evaluators.R

Only return the message of the failed evaluation

---

.travis.yml

The github version is not stable. Use the cran version instead.
PR task list:
- [NA] Update NEWS

Use cran version of sortable

---

NEWS.md
inst/lib/tutorial/tutorial.js

Use `.on("load", fn)` as `.load(fn)` has been deprecated

---

NEWS.md
R/events.R
R/http-handlers.R
R/initialize.R
docs/publishing.Rmd
docs/publishing.html

Adds `session_start` and `session_stop` events.
I originally hoped to install the session_start handler in `initialize.R` next to the stop handler. Unfortunately, we don't `initialize_session_state` (which is necessary to get the tutorial ID/name/etc) until we run a `session$registerDataObj` handler. I couldn't find a viable way to defer the session start logic until the handler had been run, so I went this route instead. (`later::later` didn't do it late enough).
```
Listening on http://127.0.0.1:6924
com.rstudio.primers.02-vis-basics (1): jeff
event: session_start
com.rstudio.primers.02-vis-basics (1): jeff
event: section_skipped
com.rstudio.primers.02-vis-basics (1): jeff
event: question_submission
com.rstudio.primers.02-vis-basics (1): jeff
event: session_stop
```
PR task list:
- NO - …

Add session start/stop events

---

docs/publishing.Rmd
docs/publishing.html

It appears that `exercise_error` in the docs is no longer valid. That string doesn't exist in the code -- at least not anymore. When I submit an invalid exercise, I get an `excercise_submission` event with an `error` field.
e.g. if I submit stop("what") in an exercise, I get this event:
```
com.rstudio.primers.02-vis-basics (1): jeff
event: exercise_submission
$label
[1] "mpg0"
$code
[1] "x <- 1\nx\nstop(\"what\")\n\nflarg"
$output
<div class="alert alert-danger" role="alert">what</div>
$error_message
[1] "what"
$checked
[1] FALSE
$feedback
NULL
```
Also fixes #327

Remove dead event, clarify Rmd/HTML docs

---

NEWS.md
inst/rmarkdown/templates/tutorial/resources/tutorial-format.js

Fixes #320 
Fixes #319 
For #320, there was never a call to notify the js data model that the section had actually been skipped.
For #319, the hash was being returned as `window.encodeURI` output.  By passing it through `window.decodeURI`, it behaves as expected.
<details>
<summary>File to test with</summary>
```
---
title: "learnr#330"
output:
learnr::tutorial:
progressive: true
allow_skip: true
---
text
text
text
text
text
text
```
</details>
* Should be able to click continue and also view the second section.

Fix progressive reveal and Topics with special characters not loading

---

R/evaluators.R
tests/testthat/test-evaluators.R

Some hosting providers will complain about a POST with no content-length.

Set a content length on session initialization request

---

NEWS.md
R/evaluators.R
R/exercise.R
man/external_evaluator.Rd

Add a limit to the "forked" evaluator (the default used on Linux) to limit the number of forked exercises that learnr will execute in parallel. Previously, this was uncapped, which could cause a learnr process to run out of memory when an influx of traffic arrived. The default limit is 3, but it can be configured using the `tutorial.max.forked.procs` option or the `TUTORIAL_MAX_FORKED_PROCS` environment variable.

Limit concurrent forks

---

R/evaluators.R
docs/openapi/openapi.yaml
tests/testthat/test-evaluators.R

When initializing a new external evaluator session, send the global setup chunk so that the process can be prepared.
Also updates the openapi spec accordingly.

Send global setup on external evaluator init

---

NEWS.md
R/evaluators.R

If an exercise had an assigned timelimit of >= 60s, it would never be reaped. This is because by default when you subtract times it becomes a `difftime` object which will be presented in arbitrary units. Around the 60s mark, you can see we switch from:
```
> str(Sys.time() - start_time)
'difftime' num 58.2525360584259
- attr(*, "units")= chr "secs"
```
to:
```
> str(Sys.time() - start_time)
'difftime' num 1.01057458321253
- attr(*, "units")= chr "mins"
```
When you compare on this time, it compares 1 to your assigned time limit and permits it to continue computing.
We need to force the time comparison into seconds in order to accurately compare to our time limit.

Properly enforce timelimits >= 60s

---

DESCRIPTION
NEWS.md
R/evaluators.R
R/events.R
R/exercise.R
docs/publishing.Rmd
docs/publishing.html
tests/testthat/test-evaluators.R

1. use the curl pool that had been created but was going unused. This will allow us to send more than 6 requests to an external evaluator at once.
2. Includes the `restore` flag on `exercise_submitted` events so that we can differentiate restored from interactive events.
3. Fixes an external evaluator bug in which we were previously waiting for EVERY request to resolve rather than just waiting for a particular request to resolve.
Closes #363

Use pool, flag restored events, resolve requests independently

---

.github/workflows/R-CMD-check.yaml
NEWS.md
R/question_text.R

Fixes #375 
Also updated Actions workflow file.
`ans$label` is an `HTML()` formatted text string. This will not match.  Instead, `ans$option` should be used as it is the raw value provided by the user.

Fix question_is_correct.learnr_text comparison

---

NEWS.md
inst/lib/tutorial/tutorial.js

Fixes #348.
---
Run the following, click the "Run Code" buttons one after another quickly. The progress spinner on both code chunks clear after 1 second, even though the `two` chunk doesn't complete for a few more seconds.
````
---
title: "Tutorial"
---
```{r setup, include=FALSE}
library(learnr)
```
```{r one, exercise=TRUE}
Sys.sleep(1); print("DONE!")
```
```{r two, exercise=TRUE}
Sys.sleep(5); print("DONE2!")
```
````
PR task list:

Fix #348: All exercises resolve to complete when one is completed

---

DESCRIPTION
R/tutorial-format.R
man/initialize_tutorial.Rd
man/tutorial.Rd

Code change https://github.com/rstudio/rmarkdown/issues/1774
Example error: https://github.com/rstudio/learnr/pull/390/checks?check_run_id=854831889#step:10:69
PR task list:

Add `smart` documentation to remove check warning

---

NEWS.md
R/knitr-hooks.R

Throw an informative error if an exercise chunk is NULL

---

NEWS.md
R/run.R

Fixes #347
Heavily inspired from #387 , but did not receive contact from OP.
PR task list:

Save tutorial output to temp folder when tutorial folder does not have write permissions

---

NEWS.md
R/http-handlers.R

See #401 for motivation.
This disables completion of R code inside quotes (when `exercise.completion = TRUE`), by setting `quotes = FALSE` in `rc.settings()`...the docs for `quotes` says:
> Enables completion in R code when inside quotes. This normally leads to filename completion, but can be otherwise depending on context (for example, when the open quote is preceded by ?), help completion is invoked. Setting this to FALSE relegates completion to the underlying completion front-end, which may do its own processing (for example, readline on Unix-alikes will do filename completion).
Thus, this might be a slightly over-agressive way to prevent filenames from being displayed. Note that there is also a `files` argument that we could set to `FALSE`, but for some reason that arg is deprecated …

Disable completion of R code inside quotes, closes #401

---

DESCRIPTION
NEWS.md
inst/lib/tutorial/tutorial.js

The prior checks (line 1437 currently) test whether or not the browser supports the necessary features, but it doesn't actually exercise whether or not we're allowed to create a store here. Some browsers (such as Safari) have additional restrictions in e.g. cross-origin iframes that preclude us from successfully opening an idb store. This check ensures that we can actually create a store, or fails fast if not.
The error caused issues whether or not idb was ultimately used as the store for learnr state.
Without this, Safari is throwing the following error:
```
[Error] SecurityError: IDBFactory.open() called in an invalid security context
open (idb-keyval-iife-compat.min.js:7:843)
e (idb-keyval-iife-compat.min.js:7:843)
(anonymous function) (tutorial.js:1518)
(anonymous function) …
```

Validate the ability to create an idb store

---

DESCRIPTION
R/learnr.R
R/shinytest.R
R/storage.R
R/utils.R
inst/lib/tutorial/tutorial.js
inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
learnr.Rproj
man/one_time.Rd

Fixes https://github.com/rstudio/shinytest/issues/209
This PR makes it possible to test learnr documents with shinytest. Should be merged after https://github.com/rstudio/shinytest/pull/321
Note: When `progressive: true` is used, there are potential timing issues after the Continue buttons are pressed, and when the Topic changes. This is because the client-side transitions take a bit of time. Users may need to add `Sys.sleep()` after setting these values for tests to work properly and consistently.
For example, here's a test script for a learnr tutorials with `progressive: true`. It required `Sys.sleep()` calls to work correctly. 
```
app <- ShinyDriver$new("../../Untitled.Rmd", seed = 50943)
app$snapshotInit("mytest")
app$setInputs(`tutorial-exercise-two-plus-two-code-editor` = list(code …
```

Add shinytest support

---

inst/examples/external/evaluator-tests.Rmd

This adds another test case for [evaluator-tests.Rmd](https://github.com/rstudio/learnr/blob/master/inst/examples/external/evaluator-tests.Rmd) taken from [grading-demo.Rmd](https://github.com/rstudio-education/gradethis/blob/6baf2d9ca584a526761ae76b0510dc274bde0561/inst/tutorials/grading-demo/grading-demo.Rmd#L261-L273) to make sure exercise checking with a `stop()` as solution works on external evaluator.

Add an exercise test case with error as solution

---

R/exercise.R
R/knitr-hooks.R
R/options.R
man/tutorial_options.Rd

Fixes #356 
Fixes #425 
Fixes https://github.com/rstudio-education/gradethis/issues/140
Related https://github.com/rstudio-education/gradethis/pull/143
After feedback from @garrettgman, and discussion with @schloerke, it's becoming apparent the `exercise.error.checker` probably isn't the right approach to exercise (evaluation) error checking.
This PR replaces `exercise.error.checker` with a slightly different option, `exercise.error.check.code`, which defines what checking code to run when an exercise error occurs. This option, in some sense, provides a global default value, which can be overridden for a particular exercise with a `-error-check` chunk. Overall this seems like a much cleaner solution than `exercise.error.checker`  since it decouples error checking code from `-code-check` …

Remove exercise.error.checker in favor of exercise.error.check.code and -error-check chunks

---

R/knitr-hooks.R

Otherwise the parent was using the child's engine
PR task list:
- [NA] Update NEWS
Before this PR, this doc did not work as chunk `even_more_setup ` was having an engine of `python`. After this PR, this document works as expected.
Example Doc:
````
---
title: "Chained setup chunks"
---
```{r setup, include = FALSE}
library(learnr)
library(reticulate)
```
```{r even_more_setup}
d <- 3
```
```{python setupA, exercise.setup = "even_more_setup"}
a = r.d + 2 # 5
```
```{r setupB, exercise.setup = "setupA"}
b <- py$a + d # 8
```
R exercise that uses `b` (via R and python setup chunks):
```{r ex1, exercise = TRUE, exercise.setup = "setupB"}
b + 1 # 9
``` …
```

Use the setup_options$engine, not options$engine.

---

R/tutorial-format.R
tests/testthat/test-tutorial-format.R

Fixes #446
Permanently disables section anchors by hard coding `anchor_sections = FALSE`.
@schloerke When a user tries to set `anchor_sections: true` the following error is thrown
```
Error in rmarkdown::html_document(smart = smart, theme = theme, lib_dir = NULL,  : 
formal argument "anchor_sections" matched by multiple actual arguments
```
Would you like me to check the `...` and throw an informative error message if `anchor_sections` is set?

Disable anchor sections for learnr tutorials

---

R/evaluators.R

Previously we'd get confused on characters like `é` since it's two bytes byt one character. If you had one such character in your message, curl would only post n-1 characters of your JSON -- leaving you with invalid JSON.

Count bytes instead of characters

---

NEWS.md
R/feedback.R
tests/testthat/test-feedback.R

This PR updates `feedback_validated()` to allow htmltools tag and tagList messages in addition to character messages.
PR task list:

Allow feedback messages to be an htmltools tag or tagList

---

NEWS.md
R/question_text.R
man/question_text.Rd
tests/testthat/test-question_text.R

Fixes https://github.com/rstudio/learnr/issues/455
This PR adds `rows` and `cols` as parameters of `question_text()`. When provided, the text input UI will use `textAreaInput()` instead of `textInput()`.
I used `rows` and `cols` as the parameter names so we can inherit documentation from `textAreaInput()`, but I'd be happy to update the parameter names or documentation to specifically mention that they change the input UI.
Here's an example to try to create an "essay" input as described in #455. The question will always be graded as incorrect, but by setting `allow_retry = TRUE` and changing the `try_again_button` text, the input feels less binary correct/incorrect.
````
---
title: "Tutorial"
---
```{r setup, include=FALSE} …

question_text() uses textAreaInput() if rows or cols are provided

---

NEWS.md
R/knitr-hooks.R
R/options.R
docs/exercises.Rmd
docs/exercises.html
docs/snippets/exercisesolutionhidden.md
man/tutorial.Rd
man/tutorial_options.Rd
tests/testthat/test-chunks-error-check.R
tests/testthat/test-options-reveal_solution.R
tests/testthat/test-setup-chunks.R
tests/testthat/tutorials/optional-show-solution.Rmd

Adds `exercise.reveal_solution`, which can be set in the `*-solution` chunk options or globally with `tutorial_options()` or `tutorial.exercise.reveal_solution`. If `FALSE`, the solution is not revealed to the user. The local chunk option takes precedence over the global option.
Fixes #402
<details><summary>Demo Tutorial</summary>
````markdown
---
title: "Optionally Reveal Exercise Solution"
---
```{r setup, include=FALSE}
library(learnr)
```
```{r default, exercise = TRUE, exercise.reveal_solution = TRUE}
1 + 1
```
```{r default-hint-1}
```
```{r default-hint-2}
```
```{r default-solution}
2
```
```{r hide, exercise = TRUE}
1 + 1
```
```{r hide-hint-1}
```
```{r hide-hint-2}
```
```{r hide-solution, exercise.reveal_solution = FALSE}
2 …

Optionally reveal (or hide) exercise solution

---

NEWS.md
R/exercise.R
tests/testthat/test-exercise.R

Drop non-list HTML dependencies from exercise html_output

---

R/exercise.R

Edit: on second thought, we were just setting `timelimit` too early. Getting the timelimit after filling out the `exercise` object fixes the issue in #492.
This fixes #492. The exercise reactive returned by `` input$`tutorial-exercise-%s-code-editor` `` doesn't include all of the exercise options. It seems that `exercise_rx()` only contains the `label`, the submitted `code`, a `timestamp` and flags for `restore` and `should_check`. The result is that, when `setup_exercise_handler` tries to find `$options$exercise.timelimit`, that field is always `NULL` because `$options` isn't a item in the reactive exercise list.
~I'm not sure if that should be rectified in the exercise object logic, but~ I was able to fix the issue by merging the reactive exercise object with the cached exercise object …

Get timelimit from complete exercise object

---

R/evaluators.R
R/exercise.R
R/identifiers.R
tests/testthat/helpers-exercise.R
tests/testthat/test-exercise.R

This PR adds a `tutorial` item to the `exercise` object with `tutorial_id`, `tutorial_version` and `user_id` (although `user_id` is scrubbed if the exercise is sent to an external evaluator). These values are added by the learnr shiny app and aren't cached as they can change at run time: https://rstudio.github.io/learnr/publishing.html#Recording_Events.
The goal is to make critical tutorial information available to the external evaluator or to exercise checking code. The motivating case is to access data hosted at a path that is constructed from the tutorial id.
PR task list:

Add tutorial id, version, and user_id to exercise object

---

inst/rmarkdown/templates/tutorial/resources/tutorial-format.htm

Fixes #499
Moved tabset initialization to later in the tutorial template to ensure that jquery is loaded before it is used to setup tabsets.

fix: Relocate tabset init in tutorial pandoc template

---

R/exercise.R
tests/testthat/helpers-exercise.R

so that exercise objects round-trip through JSON correctly.
```
jsonlite::toJSON(list(learnr_version = packageVersion("learnr")))
#> Error: No method asJSON S3 class: numeric_version
```

exercise$tutorial$learnr_version must be character

---

NEWS.md
R/exercise.R

I added a `tutorial.quick_restore` global option, that falls back to the env variable `TUTORIAL_QUICK_RESTORE`. (I'm totally open to re-naming this feature or option, btw.) When `TRUE` or `1`, submitted user code is not evaluated on the server. This will be helpful for large tutorials with many exercises; the user code is restored but the output is not evaluated.
Currently, no message or feedback is shown, so users will need to click on _Run Code_ or _Submit Answer_ to see the output in the re-loaded tutorial. I don't think this will surprise anyone. I chose not to add a message because it's not clear to me where the internationalization aspect would live for that message and the benefit to customizing or showing the message is small.
Fixes #508

Adds "quick restore" option

---

NEWS.md
inst/lib/tutorial/tutorial.js

Fixes #512. 
A note about implementation: I used `editor.getSelectedText()` to get the selected text in the editor. We're currently using `editor.getSession().getValue()` for the full code in the editor. I'm fairly certain that `editor.getSession()` is not required — I think `editor.getValue()` will return the same thing — and if it is required then we would need to follow a much more complicated way of getting the selected text.
TODO:

Run selected text if available instead of complete exercise code

---

DESCRIPTION
NEWS.md
R/exercise.R
tests/testthat/test-exercise.R

Fixes #520
This separates the exercise result object from the final HTML form returned into the learnr tutorial. I extracted the logic that concatenates the `feedback_html` and the `html_output` into a new function `exercise_result_as_html()`. The feedback is still rendered into HTML when we create the exercise result object, but we instead store it separately as `$feedback$html`.
This decouples the exercise evaluation from its final presentation.
```r
ex <- mock_exercise(
user_code = "1 + 3",
solution_code = "1 + 1",
check = "gradethis::grade_this({
gradethis::pass_if_equal(2)
gradethis::fail()
})",
exercise.checker = "gradethis::gradethis_exercise_checker"
)
result <- evaluate_exercise(ex, new.env())
result # shown as yaml
```
```yaml
feedback:
message: |
<p>Incorrect. In <code>1 + …
```

Separate feedback html from code output html in `exercise_result()`

---

NEWS.md
R/question_radio.R

Reported: https://community.rstudio.com/t/avoid-pre-selected-answers-in-learnr-multiple-choice-questions/101950
Previously, when the answer label was `"FALSE"`, that value would be selected because the default value of `selected` in `radioButtons()` was `FALSE`.
````
```{r KC-1, echo=FALSE}
question("TRUE or FALSE: My R Scripts can look sloppy as long as RStudio is able to run it.",
answer("TRUE", message = "Not quite. Think about all the *computers* you are creating computer programs for."),
answer("FALSE", correct = TRUE, message = "That's right. You should strive to make your computer programs should be interpretable by other humans as well."),
allow_retry = FALSE
)
```
````

Change default value of radio button to avoid selecting "FALSE" option

---

.github/workflows/R-CMD-check.yaml

Drops testing on windows devel, moves full matrix of testing from 3.3 to devel to ubuntu-18.04.
|version |date                |nickname               |
|:-------|:-------------------|:----------------------|
|4.1.0   |2021-05-18 07:05:22 |Camp Pontanezen        |
|4.0.0   |2020-04-24 07:05:34 |Arbor Day              |
|3.6.0   |2019-04-26 07:05:03 |Planting of a Tree     |
|3.5.0   |2018-04-23 07:04:38 |Joy in Playing         |
|3.4.0   |2017-04-21 07:14:45 |You Stupid Darkness    |
|3.3.0   |2016-05-03 07:13:28 |Supposedly Educational |

Update testing os/version matrix

---

NEWS.md
inst/lib/tutorial/tutorial.js

Correct issue in comment: https://github.com/rstudio/learnr/issues/468#issuecomment-887617871
PR task list:

Support bs4+ popover `'dispose'` method

---

R/exercise.R

Fixes #568 using `set_tutorial_state()` to correctly save the exercise state on restore

Fix storing exercise state on tutorial restore

---

DESCRIPTION

- `shinytest` 1.5.0 is available on CRAN (and is latest released version after 1.4.0.9002)
- `htmltools` 0.3.5 was released to CRAN a while ago (current CRAN version is 0.5.1.1)

Transition remote dependencies to CRAN releases

---

NEWS.md
inst/rmarkdown/templates/tutorial/resources/tutorial-format.htm

Due to the changes in rstudio/rmarkdown#2064, the HTML dependencies for learnr tutorials are now being added just before the closing `<head>` tag. This is generally a good thing, but these dependencies are inserted between custom CSS links and the closing head tag, causing the default CSS rules to be applied _over_ the custom rules rather than the other way around.
This PR uses the new `` placeholder to ensure that the default dependencies appear _before_ customm CSS.
Originally reported on RStudio Community: [learnr style appears to be broken on re-publish - shiny - RStudio Community](https://community.rstudio.com/t/learnr-style-appears-to-be-broken-on-re-publish/113435)

Include custom CSS after learnr html dependencies

---

R/tutorial-state.R
man/get_tutorial_info.Rd
tests/testthat/test-tutorial-state.R
tests/testthat/tutorials/basic.Rmd

This PR adds `tutorial_path` to `get_tutorial_info()`, which then attempts to extract the tutorial id, version and language from the source file. The information is now reported in this order:
1. Using `tutorial_path` by extracting/working with the front matter -- available only in interactive console.
2. During render using `rmarkdown::metadata` with the version of the front matter used by rmarkdown -- available only during pre-render step
3. During the running tutorial using the `session` object -- available only inside running Shiny app
I also updated some internal functions to take advantage of this new argument.

`get_tutorial_info()` can extract metadata from a tutorial's source file

---

DESCRIPTION
R/exercise.R

If it's character, assume it should be HTML and mark it as html. Otherwise if not htmltools tag or tag list, reconstruct the feedback html.
Primarily, this affects external evaluators that include `feedback$html` pre-filled but that have passed through a JSON serialization that removes the attributes and classes that mark the item as HTML. In short, external evaluators should return a character strings of HTML for pre-constructed `feedback$html`, otherwise leave the item empty (`NULL`) for it to be reconstructed by the primary tutorial app.

Use `feedback$html` if present or reconstruct otherwise

---

R/exercise.R
tests/testthat/test-exercise.R

Modifies calls to `i18n_span()` in `evaluate_exercise()` to include default English text. This provides a fallback in cases where `i18next` fails to render text.
Closes #584.

Include a default English message for blank/unparsable errors `i18n_span()`

---

NEWS.md
R/evaluators.R
tests/testthat/test-evaluators.R

As described in #339 and #449, learnr on Linux or with the forked evaluator generates a lot of `cannot wait for child...` errors when evaluating exercises. I think this warning started appearing around R 3.5 when trying to collect the results of an already collected forked job and stemmed from us calling `mccollect()` again once we already had the results.
https://github.com/rstudio/learnr/blob/b000739c03c1e3427fc3e709a49a6626b95365cb/R/evaluators.R#L94-L101
When the external evaluator was written ~5 years ago circa R 3.3, it's possible this step was required. But AFAICT from the source of `parallel::mccollect()`, this is no longer necessary. The `timeout` argument applies to _finding_ the forked process; if the process has finished it returns the complete result. Once a process …

Only collect forked evaluator results once

---

NEWS.md
R/events_default.R
inst/lib/tutorial/tutorial.js

Addresses #616 by augmenting the `exercise_submission` event to include a `completed` item. This boolean value indicates whether or not the submission should count toward the completion of the exercise and therefore the current section. This is primarily relevant when `allow_skip: false` is set in the tutorial YAML heading.
Previously, as described in #616, any exercise submission counted toward completion, including pressing "Run Code" on an empty exercise input. This will no longer be the case.
The new logic is set in the `exercise_result` event handler, which is where the `exercise_submission` event is emitted. There, we use the exercise cache to access the full exercise object and augment the `exercise_submission` event `data` with a new `completed` item. The full logic is to:
1. Only …

Refine exercise completion logic when `allow_skip = FALSE`

---

R/tutorial-format.R
inst/rmarkdown/templates/tutorial/resources/tutorial-format.htm

In preparation for upcoming changes in rmarkdown that will move the dynamically inserted `HEAD_CONTENT` to the end of the `header-includes` list.
Moves `` to just after `$header-includes$` section so that behavior before and after rstudio/rmarkdown#2249 will be more or less equivalent.

Update tutorial pandoc template for head content in header-includes

---

R/evaluators.R

It's a little noisy but I there isn't a much better place to emit this message since we call `setup_forked_evaluator_factory()` internally. Regardless, it would only be annoying for those who opt into the forked evaluator on Mac/Windows

Throw a warning from forked evaluators that behavior is inconsistent on Mac/Windows

---

tests/testthat/helpers.R
tests/testthat/test-knitr-hooks.R
tests/testthat/test-options-reveal_solution.R

Fixes tests that fail on https://rstudio.r-universe.dev for windows, which will also likely fail on CRAN, by skipping when a recent-enough version of pandoc is not available.
https://github.com/r-universe/rstudio/runs/4924603994?check_suite_focus=true

Skip tests that use pandoc if pandoc version < 1.14

---

R/tutorial-format.R
man/tutorial.Rd

This PR exposes `lib_dir` as a parameter of `tutorial()`, with a default value of `NULL`. This mirrors current behavior but unblocks users from choosing a different `lib_dir`. In general this isn't something most users want to do directly, but rather it's a problem they run into when trying to create a shiny prerendered R Markdown based website for learnr tutorials as in #510.
Closes #510 but needs https://github.com/rstudio/rmarkdown/issues/1576.

Expose `lib_dir` in `tutorial()`

---

man/rmd-fragments/hello-tutorial.Rmd
pkgdown/assets/snippets/hello-learnr.md
pkgdown/assets/snippets/snippets.js
pkgdown/index.md
vignettes/articles/exercises.Rmd
vignettes/articles/learnr.Rmd
vignettes/articles/publishing.Rmd
vignettes/articles/questions.Rmd
vignettes/articles/snippets.R

Improves the accessibility and use of snippets in the documentation, primarily in two ways:
1. We now write the snippet into the static HTML of the documentation page. The code blocks will be overwritten by the ace editor, but if for any reason the editor fails to load, the page will appear identical to other documentation that doesn't use the Ace editor.
2. When loading the editor, we keep that code block (actually we re-write it) but add `.sr-only` so that it's available for screen readers. My understanding (and testing shows) that screen readers will move over the Ace editor. Ideally, the hidden code block will be announced as if the Ace editor weren't present.

Progressively enhance docs with ace editor

---

inst/tutorials/ex-data-basics/ex-data-basics.Rmd
inst/tutorials/ex-data-filter/ex-data-filter.Rmd
inst/tutorials/ex-data-mutate/ex-data-mutate.Rmd
inst/tutorials/ex-data-summarise/ex-data-manip-summarise.Rmd

Recent changes throw an error when a `-check` chunk is used without an `exercise.checker` option (#640).
I hadn't realized that the example tutorials use `-check` chunks with simple message, which might be part of an earlier version of learnr. This PR updates the tutorials with a super basic checker that simply evaluates the `-check` chunk code and reports it as the feedback message.
This unblocks the example tutorials for now, but in the future we should update the example tutorials to use gradethis or other check packages (#650).

Fix example tutorials

---

NEWS.md
R/auto-complete.R
inst/lib/tutorial/tutorial-autocompletion.js
inst/lib/tutorial/tutorial.css
inst/lib/tutorial/tutorial.js

Currently, the exercise component traps keyboard focus when a user enters the code editor. The goal of this PR is to alleviate this problem by allowing users to press <kbd>Esc</kbd> to turn off the use of the <kbd>Tab</kbd> key for indent and outdent behavior. We also add an outline to the editor element when in this mode to visually indicate that focus has been "given back" to the container. Note that indent/outdent via <kbd>Ctrl</kbd> + <kbd>]</kbd>/<kbd>[</kbd> will still work in this mode.
Additionally, I replaced the use of anchor elements with class `btn` in the exercise toolbar with `<button>` elements. This automatically allows those buttons to receive keyboard focus as well.
Finally, a small change was needed in the autocomplete logic to ensure that the <kbd>Tab</kbd> events …

Improve keyboard navigation around exercise component

---

R/exercise.R
tests/testthat/test-exercise.R

Previously, when `render_exercise()` returns an error, we assumed it was an error created and handled in the `tryCatch()` inside `render_exercise()` around the user's code evaluation. But it's possible (a slim possibility) that `render_exercise()` might fail before we enter the `tryCatch()`.
The fix is relatively simple: we now check if we have an expected error and if not we raise an internal error.

Unexpected `render_exercise()` errors are now internal errors

---

R/exercise.R
tests/testthat/test-exercise.R

Adds a `"parse_error"` class to the error thrown when trying to parse the user's submitted code. This makes it possible for the error checker — which now gets first dibs on the parse error before the default parse error feedback is returned — to differentiate between parse errors and other errors.
```r
inherits(last_value, "parse_error")
inherits(.result, "parse_error")
```

Parse error receive "parse_error" class

---

R/staticimports.R
inst/staticexports/split_code_headers.R
tests/testthat/test-staticimports.R

There's no longer an issue if there is whitespace after first header
``` r
split_code_headers <- learnr:::split_code_headers
split_code_headers(
"# one ----  
1
2"
)
#> $one
#> [1] "1"
#> 
#> $two
#> [1] "2"
```
or if there is whitespace after subsequent headers
``` r
split_code_headers(
"# one ----
1
2"
)
#> $one
#> [1] "1"
#> 
#> $two
#> [1] "2"
```
<sup>Created on 2022-03-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
Closes #677.

Allow whitespace after code headers in `split_code_headers()`

---

R/exercise.R
tests/testthat/_snaps/exercise.md
tests/testthat/test-exercise.R

The goal here was to avoid a failure on Windows. I'm not sure if this PR directly fixes that error or if it just resolved on its own...
But this is still a good idea, since it aligns better with the intended usage of `rlang::abort()`. In short, we catch and rethrow render errors from `render_exercise()` that need to be handled in `evaluate_exercise()`. There, we may want to extract information from the original error, and we now put that in the usual place of `$parent`.

Throw render error with underlying error as `parent`

---

R/knitr-hooks.R
R/tutorial-state.R
tests/testthat/test-tutorial-state.R

Makes it easier to use extracted exercises in `evaluate_exericse()` since all of the expected pieces are now included:
* `$label` is added in the knitr hooks
* `get_tutorial_info()` adds initial exercise code as `$code` 
* `get_tutorial_info()` adds current exercise version as `$version`

`get_tutorial_info()` returns complete exercsies

---

R/exercise.R
tests/testthat/test-exercise.R

Fixes #696
Exercise chunk options that are set globally in the exercise rmd aren't allowed to appear in the exercise chunk used in the rmd. (I'm being vague because this is very deep in the internals and not user-visible.)

Remove forced chunk options from exercise chunk

---

R/evaluators.R
R/exercise.R
tests/testthat/test-evaluators.R
tests/testthat/test-exercise.R

Improve handling of external evaluator results, better error messages when conversion fails, improved tests around external evaluators.

Improve external evaluators result handling

---

NEWS.md
R/knitr-hooks.R
tests/testthat/test-knitr-hooks.R
tests/testthat/tutorials/knitr-hooks_empty-exercise/duplicate-label.Rmd
tests/testthat/tutorials/knitr-hooks_empty-exercise/empty-exercise.Rmd
tests/testthat/tutorials/knitr-hooks_empty-exercise/full-exercise.Rmd

This PR relaxes the constraint introduced in #411 that exercises must contain at least one line (even empty).
Fixes #710
There is a little bit of wonkiness that can happen with empty chunks in knitr, and I've caught the most prevalent edge cases. Still, be careful that all chunk labels are unique, especially if you use empty exercise chunks.

Allow empty exercise code chunks

---

R/exercise.R

Fixes an issue caused by persisting the `indent` chunk option during exercise render. It's relevant for pre-render, but we can always render exercises without indent, since the HTML from `render_exercise()` is injected into the container created by the pre-render. In other words, the indent context doesn't matter for exercise rendering, just document pre-render.
Problematic exercise reprex:
````markdown
- Here's a bullet point that contains an exercise:
```{r indent-ul, exercise = TRUE}
mtcars
```
```{r indent-ul-hint}
```
````

Reset `indent` chunk option during render

---

R/question_methods.R
R/quiz.R
inst/tutorials/quiz_question/quiz_question.Rmd
man/question_methods.Rd

Fixes #720 ... `question$type` may be a vector so we can't use `%in%` to compare to a set of target types.

Account for question `type` possibly being a vector

---

DESCRIPTION
R/question_checkbox.R
man/answer.Rd
man/mock_exercise.Rd
man/question_checkbox.Rd

Sets the default value of `try_again` in `question_checkbox()` to the message suggested in #731. This gives a better hint that there could be more than one answer and only when retries are allowed.
```r
question_checkbox(
"What's the best package?",
answer("tidyverse", correct = TRUE),
answer("base", correct = TRUE),
allow_retry = TRUE
)
#> Question: "What&#39;s the best package?"
#>   type: "learnr_checkbox"
#>   allow_retry: TRUE
#>   random_answer_order: FALSE
#>   answers:
#>     ✔: "tidyverse"
#>     ✔: "base"
#>   messages:
#>     correct: "Correct!"
#>     incorrect: "Incorrect"
#>     try_again: "Incorrect. Be sure to select every correct answer." 
```
https://user-images.githubusercontent.com/5420529/189210231-c1270b6e-101d-4137-b2e5-e4e35327e541.mov

Give better hint for `question_checkbox()` in `try_again` message

---

.github/CONTRIBUTING.md

Updating to point to the current CLA PDFs on rstudio.com, and to change email address people should send them to.
More on this at: https://github.com/rstudio/rstudio/issues/10609

Update CLA links and alias

---

.github/workflows/pkgdown.yaml
R/tutorial-state.R
man/get_tutorial_info.Rd

Fixes issue reported by CRAN by copying the example tutorial into the tempdir.
Fixes #737

Use temporary directory for `get_tutorial_info()` example

---

tests/testthat/test-exercise.R
tests/testthat/test-knitr-hooks.R

- Skip tests that use pandoc if >= 1.14 isn't available
- Skip Python tests on CRAN
Fixes #739

Fix Python exercise tests

---

R/exercise.R
tests/testthat/test-exercise.R

- fix(exercise_result): Fix unintentional dropping of html dependencies
- test(exercise_result): Add test for broken behavior
Fixes #744. We were unintentionally dropping html dependencies because they are not preserved through `htmltools::HTML()`.

Fix unintentional dropping of html dependencies

---

tests/testthat/test-exercise.R

Previously, tests that involved non-ASCII text were skipped on Windows, with the assumption that all Unix builds of R support UTF-8. Tests now explicitly check if the system supports UTF-8 to avoid a CRAN failure on non-Unicode Unix builds. This fix is [confirmed working on rhub's debian-clang-devel platform](https://builder.r-hub.io/status/learnr_0.11.1.9000.tar.gz-f4ea6f3709d247649483019af2aeb8c8), which forces a Latin-1 (non-UTF-8) locale.
Closes #748.

Skip non-ASCII tests if system does not support UTF-8

---

NEWS.md
R/knitr-hooks.R
tests/testthat/test-knitr-hooks.R
tests/testthat/tutorials/exercise-option-is-symbol.Rmd

Fixes #757
If symbols – like `T` or a variable – are used in the `exercise` chunk option, this would cause an error in the checks that run to validate the exercise chunk by comparing with the source chunk because the source chunk options aren't yet evaluated.
This PR evaluates the source chunk option before comparing it with our exercise chunk.

Fix issue with unevaluated `exercise` chunk option in learnr's knitr hooks

---

DESCRIPTION
NEWS.md
package.json
revdep/README.md
revdep/cran.md
vignettes/multilang.Rmd

Closes #768 (release progress moved to that issue).

Release learnr 0.11.3

---

R/quiz.R

`mark()` defaults to generating a fragment, so this way is slightly cleaner.
This is quite a trivial change, so probably not worth a mention in NEWS.
PR task list:

Use markdown::mark() instead of mark_html(options = '-standalone')

---

tests/testthat/test-exercise.R
tests/testthat/test-question_numeric.R

Fixes #780 by testing exercise errors for `"error"` class rather than `"simpleError"`.

Fix tests for exercise errors

---

NEWS.md
R/question_checkbox.R
R/question_numeric.R
R/question_radio.R
R/question_text.R
R/quiz.R
man/question_checkbox.Rd
man/quiz.Rd
tests/testthat/test-question_checkbox.R
tests/testthat/test-quiz.R

This PR extends #732 to apply to checkbox questions created by `question()` in addition to checkbox questions created by `question_checkbox()`. It does this by changing the default value of `try_again` in `question()` to `NULL`. If `try_again` is `NULL`, `question()` determines the default message based on the question `type`.
Closes #782.

Give better hint for checkbox questions created with `question()` in `try_again` message

---

NEWS.md
R/knitr-hooks.R

Fixes #795
Uses the tutorial option hook to ensure that the chunk label is always an unnamed string. This is applied globally to every chunk in a learnr tutorial and thereby avoids yihui/knitr#2280.

fix(knitr-hooks): Ensure `label` is unnamed string

---

NEWS.md
R/i18n.R
tests/testthat/helpers-i18n.R
tests/testthat/test-i18n.R

This PR simply skips checking that learnr can control the language used for R's messages in known scenarios where the `LANGUAGE` environment variable is ignored. Currently this is true for `LC_ALL="C"` and with newer versions of glibc also for `LC_ALL="C.UTF-8"`.
In an earlier iteration, I tried directly testing that if we are able to change the language of R message – by trying and succeeding or failing – but this create many more problems than it solved.
Fixes #800
Note that in the future we could maybe use `Sys.setLanguage()`, but this was added in R 4.2.0.

tests: Skip i18n message translation tests when `LC_ALL="C"` or `"C.UTF-8"`

---

DESCRIPTION
NEWS.md
R/quiz.R
R/run.R

Just removing this dependency as it is being replaced by rlang.
PR task list:

Ellipsis dependency
