docs/index.Rmd

Fixes typo

---

docs/formats.Rmd

regsion -> region, I haven't updated the pkgdown.

Fix minor typo

---

R/quiz.R
man/quiz.Rd

Example addressing functionality implemented in #146

Add example adding HTML to incorrect message

---

.Rbuildignore
.travis.yml
DESCRIPTION
R/run.R
man/safe.Rd
tests/testthat/test-safe.R

* Fixed `devtools::check()`
* Added a travis config 
* Need admin rights to turn on travis checking at https://travis-ci.org/rstudio/learnr
* May I be added as admin / collaborator for `learnr`?
(Merge with `Squash and merge` GitHub button.)

Pass `devtools::check()`

---

NEWS.md
R/tutorial-format.R
inst/rmarkdown/templates/tutorial/resources/tutorial-format.htm

Add tabset support

---

docs/publishing.Rmd

Typo in learnr publishing page

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

* Contibuting
* PR template
* Issue templates: 
* bug report
* feature request
* question.

GitHub Templates

---

NEWS.md
R/quiz.R
man/quiz.Rd

allows for extra options to be stored in a question object.  this will give a native way for extra values to be stored.
PR task list:

add options to question

---

DESCRIPTION
R/quiz.R
tests/testthat/test-question.R

* protects agains bad `...` methods.
* Improve error messages by using checkmate
* use `class(obj) <- value` instead of `structure(class = value, obj)`

use ellipsis::check_dots_unnamed on question

---

DESCRIPTION
NEWS.md
R/install_tutorial_dependencies.R
R/run.R
R/utils.R

Fixes #259 
PR task list:
cc @isteves

Install tutorial deps

---

NEWS.md
R/evaluators.R
R/exercise.R

Catch syntax errors in exercises and checker functions

---

R/install_tutorial_dependencies.R

Issue: https://github.com/rstudio/renv/issues/228
PR task list:
- [NA] Update NEWS

remove bad pkg names when finding deps

---

inst/tutorials/ex-data-basics/ex-data-basics.Rmd

* Clarifies the language throughout the document.

Copy edits ex-data-basics

---

R/question_checkbox.R
R/question_methods.R
R/quiz.R
R/quiz_print.R
R/utils.R
tests/testthat/test-mark_as.R
tests/testthat/test-question-checkbox.R
tests/testthat/test-question_messages.R

fix message logic for checkbox questions

---

DESCRIPTION
NEWS.md
README.md

* use dev version
* Update news
* Remove bad badge

Dev version 0.10.0.9000

---

NEWS.md

Add PR number for #322

---

inst/examples/external/evaluator-tests.Rmd

Just updates the suite of tests we use against external evaluators

Expand external evaluator tests

---

inst/tutorials/quiz_question/quiz_question.Rmd

In order to get the first Custom Question Types example to work, I had to modify the code in quiz_question.Rmd. The behavior of the simple answer also becomes clearer with a second answer included.

Getting simple custom question to work

---

DESCRIPTION
NEWS.md
R/http-handlers.R

Add label to exercise_hint event

Add label to exercise_hint event

---

docs/publishing.Rmd
docs/publishing.html

Add events to website

---

.github/workflows/R-CMD-check.yaml
.github/workflows/docs.yml
R/knitr-hooks.R
docs/examples.html
docs/exercises.Rmd
docs/exercises.html
docs/formats.html
docs/index.html
docs/publishing.html
docs/questions.html
docs/site_libs/navigation-1.1/codefolding.js
tests/testthat/setup-chunks/error-check-chunk_bad.Rmd
tests/testthat/setup-chunks/error-check-chunk_good.Rmd
tests/testthat/test-chunks-error-check.R

We now throw an error if an `*-error-check` chunk is provided but no `*-check` chunk is available.
Also adds a GHA workflow to build the docs on push and updates the R-CMD-check workflow to use `pak`

Check that *-error-check and *-check are both included

---

inst/tutorials/ex-data-filter/ex-data-filter.Rmd

Fixed two errors. The error in the first exercise is the most important change because the solution is wrong (it says to do less than 2 minutes, instead of less than 120 (2 hours)). This is my first pull request ever so please forgive mistakes.
This is meant to be an improvement in the built-in RStudio Tutorial, not to the learnr package in general. 
PR task list:

Fix hours example in ex-data-filter.Rmd

---

inst/lib/tutorial/tutorial.js

Need to capture the count in the element directly so it's available when translating after first init

Fix pluralization of exercise helper buttons after first init

---

inst/tutorials/ex-data-mutate/ex-data-mutate.Rmd

Fix exercise solution in ex-data-mutate.
The original solution code was not executable, so I made a very minor change.

Fix exercise solution in ex-data-mutate

---

inst/lib/i18n/tutorial-i18n-init.js
inst/lib/tutorial/tutorial.js

- jQuery'ified `tutorial-i18n-init.js`
- Clear focus from editor after `setValue()` when in a shinytest session.
`learnr-issue-209.Rmd`
````markdown
---
title: "Tutorial"
output: 
learnr::tutorial:
progressive: true
---
```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```
*Here's a simple exercise with an empty code chunk provided for entering the answer.*
Write the R code required to add two plus two:
```{r two-plus-two, exercise=TRUE}
```
*Here's an exercise with some prepopulated code as well as `exercise.lines = 5` to provide a bit more initial room to work.*
Now write a function that adds any two numbers and then call it:
```{r add-function, exercise=TRUE, exercise.lines = 5}
add <- function() {
}
```
*Here's an exercise where …
```

Update learnr for compatibility with shinytest

---

inst/tutorials/ex-data-filter/ex-data-filter.Rmd

Suggest changing "Submit Answer" to "Run Code" to avoid confusion in the `filter()` section.

Fix exercise prompt in ex-data-filter.Rmd

---

.github/workflows/pr-commands.yaml

Run `/document` on `ubuntu-18.04` and fix name of `/i18nize` job

Fix PR command runners

---

DESCRIPTION
R/exercise.R
tests/testthat/test-exercise.R

PR task list:
- [NA] Update NEWS

When rendering exercises, disable select sys env vars and disable shiny domain

---

.github/workflows/R-CMD-check.yaml

- [ci] Also run on `main` branch
- [ci] Share GITHUB_PAT with shinyapps deploy job
- [ci] shinyapps deploy only runs on ubuntu-18.04

[ci] Update shinyapps.io deploy job

---

DESCRIPTION

Increment dev version to v0.10.1.9012

Bump dev version v0.10.1.9012

---

data-raw/i18n_translations.yml

Adds German translation for learnr's interface

Add German translations for learnr interface

---

data-raw/i18n_random-phrases.yml

Adds random praise/encouragement in German

Add random phrases in German

---

inst/tutorials/quiz_question/quiz_question.Rmd

Minor documentation adjustment to include explicit S3 method registration. See #722

Improve `quiz_question` S3 method registration in docs

---

DESCRIPTION
LICENSE.md

- Update Alex's role to author
- Update `@rstudio.com` email addresses to `@posit.co`
- RStudio is now Posit in description and license

Alex is an author and RStudio is now Posit
